### PR TITLE
cl-emoji has multiple emoji list for several versions

### PR DESCRIPTION
**Pull request by t-sin**
Hi.

This pull request makes cl-emoji have multiple emoji list for several emoji versions.

This is related #1:

> When Emoji v5.0 is released, how is cl-emoji updated? I consider there is two ways:
> 
> 1. cl-emoji follows latest version, simply
> 2. cl-emoji supports some versions. User specify emoji version when he/she use cl-emoji

On this pull request, I choose `2.`, and add Unicode 10.0 (Emoji 5.0, CLDR 31) emoji list.

I set default emoji version Emoji 4.0, CLDR 31, however, users can use Emoji 5.0 and CLDR 31 with `cl-emoji:init-emoji` function. 

I hope that this PR makes you grad.

### CODE REVIEW

**Comment by tani** [comment]
I really appreciate it and have a question. 
There are `*emoji-list*` as global variable in your PR. 
`*emoji-list*` has a ton of items if ever cl-emoji's function isn't used.

What do you think about it?

**Comment by t-sin** [comment]
Thanks for your comment!

I quite agree: `*emoji-list*` feels so huge, especially when cl-emoji's APIs are not called.
Also now I understand emoji-list loading philosophy. 

I'll fix it.

**Comment by t-sin** [comment]
Fixed!

And users can access version information.

**Comment by t-sin** [comment]
Commits above maybe makes #3 conflict. If this PR is merged, I will resolve that confliction on #3.

**Comment by tani** [comment]
Thank you! Thank you! Thank you! And thank you!
I will merge your PR of #3 if you resolve that.

BTW I'll upload this project to Quicklisp.

**Comment by t-sin** [comment]
> BTW I'll upload this project to Quicklisp.

Wow wow wonderful! 👍 😁 ❤️ 🍻

**Pull request merged**
